### ISSUE TITLE
doSOCS Database Schema

### ISSUE THREAD

**Issue by DanPatten** [vkambhampaty/SPDX-2.0#1]
In order for the teams to implement doSOCS, the mysql database schema must be imported from SOCSDatabase (https://github.com/socs-dev-env/SOCSDatabase/blob/master/SQL/SPDX.sql)

You may notice that you have similar tables between both schemas including spdx_file and spdx_docs. In order for doSOCS to work correctly, the table names need to be from SOCSDatabase. It would be useful to merge these together in a meaningful way to provide backwards compatibility with doSOCS.

**Comment by RohithGali** [comment]
We need to have access to doSOCS Database in order to do that. We will talk to Matt and resolve this issue.

**Comment by RohithGali** [comment]
You can find the updated schema in the following link of the SOCS repo 
https://github.com/socs-dev-env/Database-SPDX2.0
hope this'll help for the time being.
