### ISSUE TITLE
Unable to create table: `spdx_file_info`

### ISSUE THREAD

**Issue by jmoverkamp** [vkambhampaty/SPDX-2.0#2]
MySQL Version: 5.5.8

Creating the table `spdx_file_info` with all of it's attributes/constraints generates the error:

"#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'bigserial, fspdx_id text NOT NULL, filename  text, filetype text, ' at line 2"

**Comment by ghost** [comment]
The issue is that MySQL does not know what 'bigserial' is; that's an auto-incrementing data type supported by PostgreSQL.

My suggestion would be to replace 'bigserial' with 'integer', if only because all the other tables use 'integer' primary key fields. I'm verifying this fix now.

**Comment by RohithGali** [comment]
The typos have been changed. Thanks for the suggestions.
