### ISSUE TITLE
2 tables with same instances "spdx_license_list" and "spdx_license_list_insert"!

### ISSUE THREAD

**Issue by hangal2001** [vkambhampaty/SPDX-2.0#3]
For the consistency, we should stick with only one table containing the spdx license lists. "spdx_license_list"

**Comment by RohithGali** [comment]
Yes...actually that particular table was inserted twice by mistake. It will be removed as early as possible and we can close the issue

**Comment by vkambhampaty** [comment]
The changes have been made.
