### ISSUE TITLE
Addition of AUTO_INCREMENT primary key values

### ISSUE THREAD

**Issue by jmoverkamp** [vkambhampaty/SPDX-2.0#6]
In the previous database we worked off of, all primary key values were set to auto increment. This specification was left out of the 2.0 database. 

The keys that this might pertain to would be:
annotator_info_pk in spdx_annotations_create
identifier in spdx_extracted_lic_info
spdx_pk in spdx_file
file_info_pk in spdx_file_info
package_info_pk in spdx_package_info
relationships_info_pk in spdx_relationships_create

In addition, the default value of 0 could then be removed from these attributes.

Thank you for your consideration.

**Comment by RohithGali** [comment]
all the primary key values have been changed to auto increment.
